name: CI/CD - Develop (Vercel Preview)

on:
  push:
    branches:
      - develop

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Vercel (develop)
        id: vercel_deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID  }}
          working-directory: ./
          scope: ${{ secrets.VERCEL_ORG_ID }}
      - name: 🧪Comment deployment URL
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: vercel-preview
          message: |
            ✅ **Vercel Preview Deployment Successful!**
            🔗 [View Deployment](${{ steps.vercel_deploy.outputs.preview-url }})
