name: CI/CD - Production

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build Next.js app
        run: npm run build

      # Optional: Require manual approval before deploy (protection)
      - name: Wait for manual approval
        if: github.ref == 'refs/heads/main'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: cinblockchain91 # người được phép approve deploy

      - name: Deploy to Vercel (production)
        id: vercel_deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          scope: ${{ secrets.VERCEL_ORG_ID }}
      - name: 🚀Comment production URL
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: vercel-prod
          message: |
            🎉 **Production Deployment Successful!**
            🌍 [Live Site](${{ steps.vercel_deploy.outputs.preview-url }})
